#pragma once

#include "Def_Enum.h"
#include "Def_CompileOption.h"

#if(SET_INSPECTOR == SYS_TLA_ASSEMBLE)			// SYS_TLA_ASSEMBLE
#pragma region TLAAssemble
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("긴급 정지 버튼"),
	_T("전원 끄기 버튼"),
	_T("메인 압력"),
	_T("슬립 모드"),
	_T("초기화 버튼"),
	_T(""),
	_T("시작"),
	_T("정지"),
	_T("에어리어"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""), 
	_T("전면도어1 인터락 온/오프"),
	_T("전면도어1 열림/닫힘"),


	_T("왼쪽도어 1 인터락 온/오프"),
	_T("왼쪽도어 1 열림/닫힘"),
	_T("왼쪽도어 2 인터락 온/오프"),
	_T("왼쪽도어 2 열림/닫힘"),
	_T("왼쪽도어 3 인터락 온/오프"),
	_T("왼쪽도어 3 열림/닫힘"),
	_T("오른쪽도어 1 인터락 온/오프"),
	_T("오른쪽도어 1 열림/닫힘"),
	_T("오른쪽도어 2 인터락 온/오프"),
	_T("오른쪽도어 2 열림/닫힘"),
	_T("오른쪽도어 3 인터락 온/오프"),
	_T("오른쪽도어 3 열림/닫힘"),
	_T("후면도어 1 인터락 온/오프"),
	_T("후면도어 1 열림/닫힘"),
	_T("후면도어 2 인터락 온/오프"),
	_T("후면도어 2 열림/닫힘"),

	_T("제품 안착 감지 왼쪽"),
	_T("제품 안착 감지 오른쪽"),
	_T(""),
	_T("제품고정 왼쪽 업"),
	_T("제품고정 왼쪽 다운"),
	_T(""),
	_T("제품고정 오른쪽 업"),
	_T("제품고정 오른쪽 다운"),
	_T("-"),
	_T("조정부 전진"),
	_T("조정부 후진"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("L 드라이버 토크지그 고정 L"),
	_T("L 드라이버 토크지그 고정 R"),
	_T("L 토크지그 안착 확인"),
	_T("L 토크지그 전진 확인"),
	_T("L 토크지그 후진 확인"),
	_T(""),
	_T("R 드라이버 토크지그 고정 L"),
	_T("R 드라이버 토크지그 고정 R"),
	_T("R 토크지그 안착 확인"),
	_T("R 토크지그 전진 확인"),
	_T("R 토크지그 후진 확인"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("L 드라이버 신호 0"),
	_T("L 드라이버 신호 1"),
	_T("L 드라이버 신호 2"),
	_T("L 드라이버 신호 3"),
	_T("L 드라이버 신호 4"),
	_T("L 드라이버 신호 5"),
	_T("L 드라이버 신호 6"),
	_T("L 드라이버 신호 7"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("R 드라이버 신호 0"),
	_T("R 드라이버 신호 1"),
	_T("R 드라이버 신호 2"),
	_T("R 드라이버 신호 3"),
	_T("R 드라이버 신호 4"),
	_T("R 드라이버 신호 5"),
	_T("R 드라이버 신호 6"),
	_T("R 드라이버 신호 7"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("")
};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("EMO"),
	_T("Power Off"),
	_T("Main Air Pressure"),
	_T("Sleep Mode On Sensor"),
	_T("INIT Button"),
	_T(""),
	_T("START Button"),
	_T("STOP Button"),
	_T("AREA Sensor"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("Front Door1 Lock"),
	_T("Front Door1 Open / Close"),

	_T("Side Left Door1 Lock"),
	_T("Side Left Door1 Open / Close"),
	_T("Side Left Door2 Lock"),
	_T("Side Left Door2 Open / Close"),
	_T("Side Left Door3 Lock"),
	_T("Side Left Door3 Open / Close"),
	_T("Side Right Door1 Lock"),
	_T("Side Right Door1 Open / Close"),
	_T("Side Right Door2 Lock"),
	_T("Side Right Door2 Open / Close"),
	_T("Side Right Door3 Lock"),
	_T("Side Right Door3 Open / Close"),
	_T("Rear Door1 Lock"),
	_T("Rear Door1 Open / Close"),
	_T("Rear Door2 Lock"),
	_T("Rear Door2 Open / Close"),

	_T("STAU Product L Check Sensor"),
	_T("STAU Product R Check Sensor"),
	_T(""),
	_T("STAU Lock in L Sensor"),
	_T(""),
	_T(""),
	_T("STAU Lock in R Sensor"),
	_T(""),
	_T(""),
	_T("STAU Chuck Fwd Sensor"),
	_T("STAU Chuck Bwd Sensor"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("DBUL Jig L Lock Down Sensor"),
	_T("DBUL Jig R Lock Down Sensor"),
	_T("DBUL Jig Load Check Sensor"),
	_T("DBUL Jig In Check Sensor"),
	_T("DBUL Jig Out Check Sensor"),
	_T(""),
	_T("DBUR Jig L Lock Down Sensor"),
	_T("DBUR Jig R Lock Down Sensor"),
	_T("DBUR Jig Load Check Sensor"),
	_T("DBUR Jig In Check Sensor"),
	_T("DBUR Jig Out Check Sensor"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("DBUL Driver L 0"),
	_T("DBUL Driver L 1"),
	_T("DBUL Driver L 2"),
	_T("DBUL Driver L 3"),
	_T("DBUL Driver L 4"),
	_T("DBUL Driver L 5"),
	_T("DBUL Driver L 6"),
	_T("DBUL Driver L 7"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("DBUR Driver R 0"),
	_T("DBUR Driver R 1"),
	_T("DBUR Driver R 2"),
	_T("DBUR Driver R 3"),
	_T("DBUR Driver R 4"),
	_T("DBUR Driver R 5"),
	_T("DBUR Driver R 6"),
	_T("DBUR Driver R 7"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("-"),
	_T("슬립 모드"),
	_T("-"),
	_T("초기화 버튼"),
	_T("리셋 버튼"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("-"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("전면도어1 인터락 On/Off"),
	_T("-"),

	_T("왼쪽도어 1 인터락 On/Off"),
	_T(""),
	_T("왼쪽도어 2 인터락 On/Off"),
	_T(""),
	_T("왼쪽도어 3 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 1 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 2 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 3 인터락 On/Off"),
	_T(""),
	_T("후면도어 1 인터락 On/Off"),
	_T(""),
	_T("후면도어 2 인터락 On/Off"),
	_T(""),


	_T("조정 그립/언그립"),
	_T(""),
	_T(""),
	_T("제품고정 업"),
	_T("제품고정 다운"),
	_T(""),
	_T(""),
	_T(""),
	_T("-"),
	_T("조정부 전진"),
	_T("조정부 후진"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("L 드라이버 토크지그 풀림"),
	_T("L 드라이버 토크지그 고정"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("R 드라이버 토크지그 풀림"),
	_T("R 드라이버 토크지그 고정"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("L 드라이버 조정 0"),
	_T("L 드라이버 조정 1"),
	_T("L 드라이버 조정 2"),
	_T("L 드라이버 조정 3"),
	_T("L 드라이버 조정 4"),
	_T("L 드라이버 조정 5"),
	_T("L 드라이버 조정 6"),
	_T("L 드라이버 조정 7"),
	_T("L 드라이버 조정 8"),
	_T("L 드라이버 조정 9"),
	_T("L 드라이버 조정 10"),
	_T("L 드라이버 조정 11"),
	_T("L 드라이버 조정 12"),
	_T(""),
	_T(""),
	_T(""),

	_T("R 드라이버 조정 0"),
	_T("R 드라이버 조정 1"),
	_T("R 드라이버 조정 2"),
	_T("R 드라이버 조정 3"),
	_T("R 드라이버 조정 4"),
	_T("R 드라이버 조정 5"),
	_T("R 드라이버 조정 6"),
	_T("R 드라이버 조정 7"),
	_T("R 드라이버 조정 8"),
	_T("R 드라이버 조정 9"),
	_T("R 드라이버 조정 10"),
	_T("R 드라이버 조정 11"),
	_T("R 드라이버 조정 12"),
	_T(""),
	_T(""),
	_T(""),


};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("-"),
	_T("Sleep Mode On"),
	_T("-"),
	_T("Init Lamp"),
	_T("Reset Lamp"),
	_T("START Lamp"),
	_T("STOP Lamp"),
	_T("-"),
	_T("Towerlamp Red"),
	_T("Towerlamp Yellow"),
	_T("Towerlamp Green"),
	_T("Towerlamp Beep1"),
	_T("Towerlamp Beep2"),
	_T("Front Door1 Lock/Unlock"),
	_T(""),

	_T("Side Left Door1 Lock/Unlock"),
	_T(""),
	_T("Side Left Door2 Lock/Unlock"),
	_T(""),
	_T("Side Left Door3 Lock/Unlock"),
	_T(""),
	_T("Side Right Door1 Lock/Unlock"),
	_T(""),
	_T("Side Right Door2 Lock/Unlock"),
	_T(""),
	_T("Side Right Door3 Lock/Unlock"),
	_T(""),
	_T("Rear Door1 Lock/Unlock"),
	_T(""),
	_T("Rear Door2 Lock/Unlock"),
	_T(""),

	_T("STAU Chuck Grip"),
	_T(""),
	_T(""),
	_T("STAU Lock in"),
	_T("STAU Lock Out"),
	_T(""),
	_T(""),
	_T(""),
	_T("-"),
	_T("STAU Chuck Fwd"),
	_T("STAU Chuck Bwd"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("DBUL Jig Lock Up"),
	_T("DBUL Jig Lock Down"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("DBUR Jig Lock Up"),
	_T("DBUR Jig Lock Down"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T("DBUL Driver L 0"),
	_T("DBUL Driver L 1"),
	_T("DBUL Driver L 2"),
	_T("DBUL Driver L 3"),
	_T("DBUL Driver L 4"),
	_T("DBUL Driver L 5"),
	_T("DBUL Driver L 6"),
	_T("DBUL Driver L 7"),
	_T("DBUL Driver L 8"),
	_T("DBUL Driver L 9"),
	_T("DBUL Driver L 10"),
	_T("DBUL Driver L 11"),
	_T("DBUL Driver L 12"),
	_T(""),
	_T(""),
	_T(""),

	_T("DBUL Driver R 0"),
	_T("DBUL Driver R 1"),
	_T("DBUL Driver R 2"),
	_T("DBUL Driver R 3"),
	_T("DBUL Driver R 4"),
	_T("DBUL Driver R 5"),
	_T("DBUL Driver R 6"),
	_T("DBUL Driver R 7"),
	_T("DBUL Driver R 8"),
	_T("DBUL Driver R 9"),
	_T("DBUL Driver R 10"),
	_T("DBUL Driver R 11"),
	_T("DBUL Driver R 12"),
	_T(""),
	_T(""),
	_T("")
};

enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_EMO = 0,
	DIO_INPUT_X0_01_POWER_OFF,
	DIO_INPUT_X0_02_MAIN_PRESSURE,
	DIO_INPUT_X0_03_SLEEP_MODE,
	DIO_INPUT_X0_04_INIT,
	DIO_INPUT_X0_05_SPARE,
	DIO_INPUT_X0_06_START,
	DIO_INPUT_X0_07_STOP,
	DIO_INPUT_X0_08_AREA,
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SPARE,
	DIO_INPUT_X0_0C_SPARE,
	DIO_INPUT_X0_0D_SPARE,
	//
	DIO_INPUT_X0_0E_FRONT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_0F_FRONT_DOOR1_INTERLOCK_OPEN_CLOSE,

	DIO_INPUT_X0_10_SIDE_LEFT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_11_SIDE_LEFT_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_12_SIDE_LEFT_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_13_SIDE_LEFT_DOOR2_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_14_SIDE_LEFT_DOOR3_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_15_SIDE_LEFT_DOOR3_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_16_SIDE_RIGHT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_17_SIDE_RIGHT_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_18_SIDE_RIGHT_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_19_SIDE_RIGHT_DOOR2_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1A_SIDE_RIGHT_DOOR3_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1B_SIDE_RIGHT_DOOR3_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1C_REAR_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1D_REAR_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1E_REAR_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1F_REAR_DOOR2_INTERLOCK_OPEN_CLOSE,
	//
	DIO_INPUT_X1_00_STAU_PRODUCT_L_SENSOR,
	DIO_INPUT_X1_01_STAU_PRODUCT_R_SENSOR,
	DIO_INPUT_X1_02_SPARE,
	DIO_INPUT_X1_03_STAU_L_CYL_IN_CHK_SENSOR,
	DIO_INPUT_X1_04_SPARE,
	DIO_INPUT_X1_05_SPARE,
	DIO_INPUT_X1_06_STAU_R_CYL_IN_CHK_SENSOR,
	DIO_INPUT_X1_07_SPARE,
	DIO_INPUT_X1_08_SPARE,
	DIO_INPUT_X1_09_STAU_CHUCK_FWD_IN_CHK_SENSOR,
	DIO_INPUT_X1_0A_STAU_CHUCK_BWD_IN_CHK_SENSOR,
	DIO_INPUT_X1_0B_SPARE,
	DIO_INPUT_X1_0C_SPARE,
	DIO_INPUT_X1_0D_SPARE,
	DIO_INPUT_X1_0E_SPARE,
	DIO_INPUT_X1_0F_SPARE,

	DIO_INPUT_X1_10_DBUL_JIG_L_CYL_DOWN_CHK_SENSOR,
	DIO_INPUT_X1_11_DBUL_JIG_R_CYL_DOWN_CHK_SENSOR,
	DIO_INPUT_X1_12_DBUL_JIG_LOAD_CHK_SENSOR,
	DIO_INPUT_X1_13_DBUL_JIG_IO_IN_CHK_SENSOR,
	DIO_INPUT_X1_14_DBUL_JIG_IO_OUT_CHK_SENSOR,
	DIO_INPUT_X1_15_SPARE,
	DIO_INPUT_X1_16_DBUR_JIG_L_CYL_DOWN_CHK_SENSOR,
	DIO_INPUT_X1_17_DBUR_JIG_R_CYL_DOWN_CHK_SENSOR,
	DIO_INPUT_X1_18_DBUR_JIG_LOAD_CHK_SENSOR,
	DIO_INPUT_X1_19_DBUR_JIG_IO_IN_CHK_SENSOR,
	DIO_INPUT_X1_1A_DBUR_JIG_IO_OUT_CHK_SENSOR,
	DIO_INPUT_X1_1B_SPARE,
	DIO_INPUT_X1_1C_SPARE,
	DIO_INPUT_X1_1D_SPARE,
	DIO_INPUT_X1_1E_SPARE,
	DIO_INPUT_X1_1F_SPARE,

	DIO_INPUT_X2_00_DBUL_DRIVER_L_0,
	DIO_INPUT_X2_01_DBUL_DRIVER_L_1,
	DIO_INPUT_X2_02_DBUL_DRIVER_L_2,
	DIO_INPUT_X2_03_DBUL_DRIVER_L_3,
	DIO_INPUT_X2_04_DBUL_DRIVER_L_4,
	DIO_INPUT_X2_05_DBUL_DRIVER_L_5,
	DIO_INPUT_X2_06_DBUL_DRIVER_L_6,
	DIO_INPUT_X2_07_DBUL_DRIVER_L_7,
	DIO_INPUT_X2_08_SPARE,
	DIO_INPUT_X2_09_SPARE,
	DIO_INPUT_X2_0A_SPARE,
	DIO_INPUT_X2_0B_SPARE,
	DIO_INPUT_X2_0C_SPARE,
	DIO_INPUT_X2_0D_SPARE,
	DIO_INPUT_X2_0E_SPARE,
	DIO_INPUT_X2_0F_SPARE,
			   	   
	DIO_INPUT_X2_10_DBUR_DRIVER_R_0,
	DIO_INPUT_X2_11_DBUR_DRIVER_R_1,
	DIO_INPUT_X2_12_DBUR_DRIVER_R_2,
	DIO_INPUT_X2_13_DBUR_DRIVER_R_3,
	DIO_INPUT_X2_14_DBUR_DRIVER_R_4,
	DIO_INPUT_X2_15_DBUR_DRIVER_R_5,
	DIO_INPUT_X2_16_DBUR_DRIVER_R_6,
	DIO_INPUT_X2_17_DBUR_DRIVER_R_7,
	DIO_INPUT_X2_18_SPARE,
	DIO_INPUT_X2_19_SPARE,
	DIO_INPUT_X2_1A_SPARE,
	DIO_INPUT_X2_1B_SPARE,
	DIO_INPUT_X2_1C_SPARE,
	DIO_INPUT_X2_1D_SPARE,
	DIO_INPUT_X2_1E_SPARE,
	DIO_INPUT_X2_1F_SPARE
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_SPARE,
	DIO_OUTPUT_Y0_03_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_02_SPARE,
	DIO_OUTPUT_Y0_04_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_06_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_07_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_08_SPARE,
	DIO_OUTPUT_Y0_09_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_0B_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_0C_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0D_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0E_FRONT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_0F_SPARE,

	DIO_OUTPUT_Y0_10_SIDE_LEFT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_11_SPARE,
	DIO_OUTPUT_Y0_12_SIDE_LEFT_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_13_SPARE,
	DIO_OUTPUT_Y0_14_SIDE_LEFT_DOOR3_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_15_SPARE,
	DIO_OUTPUT_Y0_16_SIDE_RIGHT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SIDE_RIGHT_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SIDE_RIGHT_DOOR3_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_REAR_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1D_SPARE,
	DIO_OUTPUT_Y0_1E_REAR_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1F_SPARE,

	DIO_OUTPUT_Y1_00_STAU_CHUCK_GRIP,
	DIO_OUTPUT_Y1_01_SPARE,
	DIO_OUTPUT_Y1_02_SPARE,
	DIO_OUTPUT_Y1_03_STAU_CYL_UP,
	DIO_OUTPUT_Y1_04_STAU_CYL_DOWN,
	DIO_OUTPUT_Y1_05_SPARE,
	DIO_OUTPUT_Y1_06_SPARE,
	DIO_OUTPUT_Y1_07_SPARE,
	DIO_OUTPUT_Y1_08_SPARE,
	DIO_OUTPUT_Y1_09_STAU_CHUCK_FWD,
	DIO_OUTPUT_Y1_0A_STAU_CHUCK_BWD,
	DIO_OUTPUT_Y1_0B_SPARE,
	DIO_OUTPUT_Y1_0C_SPARE,
	DIO_OUTPUT_Y1_0D_SPARE,
	DIO_OUTPUT_Y1_0E_SPARE,
	DIO_OUTPUT_Y1_0F_SPARE,

	DIO_OUTPUT_Y1_10_DBUL_JIG_L_CYL_UP,
	DIO_OUTPUT_Y1_11_DBUL_JIG_L_CYL_DOWN,
	DIO_OUTPUT_Y1_12_SPARE,
	DIO_OUTPUT_Y1_13_SPARE,
	DIO_OUTPUT_Y1_14_SPARE,
	DIO_OUTPUT_Y1_15_SPARE,
	DIO_OUTPUT_Y1_16_DBUR_JIG_R_CYL_UP,
	DIO_OUTPUT_Y1_17_DBUR_JIG_R_CYL_DOWN,
	DIO_OUTPUT_Y1_18_SPARE,
	DIO_OUTPUT_Y1_19_SPARE,
	DIO_OUTPUT_Y1_1A_SPARE,
	DIO_OUTPUT_Y1_1B_SPARE,
	DIO_OUTPUT_Y1_1C_SPARE,
	DIO_OUTPUT_Y1_1D_SPARE,
	DIO_OUTPUT_Y1_1E_SPARE,
	DIO_OUTPUT_Y1_1F_SPARE,


	DIO_OUTPUT_Y2_00_DBUL_DRIVER_L_0,
	DIO_OUTPUT_Y2_01_DBUL_DRIVER_L_1,
	DIO_OUTPUT_Y2_02_DBUL_DRIVER_L_2,
	DIO_OUTPUT_Y2_03_DBUL_DRIVER_L_3,
	DIO_OUTPUT_Y2_04_DBUL_DRIVER_L_4,
	DIO_OUTPUT_Y2_05_DBUL_DRIVER_L_5,
	DIO_OUTPUT_Y2_06_DBUL_DRIVER_L_6,
	DIO_OUTPUT_Y2_07_DBUL_DRIVER_L_7,
	DIO_OUTPUT_Y2_08_DBUL_DRIVER_L_8,
	DIO_OUTPUT_Y2_09_DBUL_DRIVER_L_9,
	DIO_OUTPUT_Y2_0A_DBUL_DRIVER_L_10,
	DIO_OUTPUT_Y2_0B_DBUL_DRIVER_L_11,
	DIO_OUTPUT_Y2_0C_DBUL_DRIVER_L_12,
	DIO_OUTPUT_Y2_0D_SPARE,
	DIO_OUTPUT_Y2_0E_SPARE,
	DIO_OUTPUT_Y2_0F_SPARE,

	DIO_OUTPUT_Y2_10_DBUR_DRIVER_R_0,
	DIO_OUTPUT_Y2_11_DBUR_DRIVER_R_1,
	DIO_OUTPUT_Y2_12_DBUR_DRIVER_R_2,
	DIO_OUTPUT_Y2_13_DBUR_DRIVER_R_3,
	DIO_OUTPUT_Y2_14_DBUR_DRIVER_R_4,
	DIO_OUTPUT_Y2_15_DBUR_DRIVER_R_5,
	DIO_OUTPUT_Y2_16_DBUR_DRIVER_R_6,
	DIO_OUTPUT_Y2_17_DBUR_DRIVER_R_7,
	DIO_OUTPUT_Y2_18_DBUR_DRIVER_R_8,
	DIO_OUTPUT_Y2_19_DBUR_DRIVER_R_9,
	DIO_OUTPUT_Y2_1A_DBUR_DRIVER_R_10,
	DIO_OUTPUT_Y2_1B_DBUR_DRIVER_R_11,
	DIO_OUTPUT_Y2_1C_DBUR_DRIVER_R_12,
	DIO_OUTPUT_Y2_1D_SPARE,
	DIO_OUTPUT_Y2_1E_SPARE,
	DIO_OUTPUT_Y2_1F_SPARE
};
#pragma  endregion
#elif(SET_INSPECTOR == SYS_TLA_OQC)		// SYS_TLA_OQC
#pragma region TLAOQC
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("긴급 정지 버튼"),
	_T("전원 끄기 버튼"),
	_T("메인 압력"),
	_T("슬립 모드"),
	_T("초기화 버튼"),
	_T(""),
	_T("시작"),
	_T("정지"),
	_T("에어리어"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("전면도어1 인터락 온/오프"),
	_T("전면도어1 열림/닫힘"),


	_T("왼쪽도어 1 인터락 온/오프"),
	_T("왼쪽도어 1 열림/닫힘"),
	_T("왼쪽도어 2 인터락 온/오프"),
	_T("왼쪽도어 2 열림/닫힘"),
	_T("왼쪽도어 3 인터락 온/오프"),
	_T("왼쪽도어 3 열림/닫힘"),
	_T("오른쪽도어 1 인터락 온/오프"),
	_T("오른쪽도어 1 열림/닫힘"),
	_T("오른쪽도어 2 인터락 온/오프"),
	_T("오른쪽도어 2 열림/닫힘"),
	_T("오른쪽도어 3 인터락 온/오프"),
	_T("오른쪽도어 3 열림/닫힘"),
	_T("후면도어 1 인터락 온/오프"),
	_T("후면도어 1 열림/닫힘"),
	_T("후면도어 2 인터락 온/오프"),
	_T("후면도어 2 열림/닫힘"),

	_T("제품 안착 감지 왼쪽"),
	_T("제품 안착 감지 오른쪽"),
	_T(""),
	_T("제품고정 왼쪽 업"),
	_T("제품고정 왼쪽 다운"),
	_T(""),
	_T("제품고정 오른쪽 업"),
	_T("제품고정 오른쪽 다운"),
	_T("-"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),


};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("EMO"),
	_T("Power Off"),
	_T("Main Air Pressure"),
	_T("Sleep Mode On Sensor"),
	_T("INIT Button"),
	_T(""),
	_T("START Button"),
	_T("STOP Button"),
	_T("AREA Sensor"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("Front Door1 Lock"),
	_T("Front Door1 Open / Close"),

	_T("Side Left Door1 Lock"),
	_T("Side Left Door1 Open / Close"),
	_T("Side Left Door2 Lock"),
	_T("Side Left Door2 Open / Close"),
	_T("Side Left Door3 Lock"),
	_T("Side Left Door3 Open / Close"),
	_T("Side Right Door1 Lock"),
	_T("Side Right Door1 Open / Close"),
	_T("Side Right Door2 Lock"),
	_T("Side Right Door2 Open / Close"),
	_T("Side Right Door3 Lock"),
	_T("Side Right Door3 Open / Close"),
	_T("Rear Door1 Lock"),
	_T("Rear Door1 Open / Close"),
	_T("Rear Door2 Lock"),
	_T("Rear Door2 Open / Close"),

	_T("STAU Product L Check Sensor"),
	_T("STAU Product R Check Sensor"),
	_T(""),
	_T("STAU Lock in L Sensor"),
	_T(""),
	_T(""),
	_T("STAU Lock in R Sensor"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("-"),
	_T("-"),
	_T("슬립 모드"),
	_T("초기화 버튼"),
	_T("리셋 버튼"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("-"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("전면도어1 인터락 On/Off"),
	_T("-"),

	_T("왼쪽도어 1 인터락 On/Off"),
	_T(""),
	_T("왼쪽도어 2 인터락 On/Off"),
	_T(""),
	_T("왼쪽도어 3 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 1 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 2 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 3 인터락 On/Off"),
	_T(""),
	_T("후면도어 1 인터락 On/Off"),
	_T(""),
	_T("후면도어 2 인터락 On/Off"),
	_T(""),


	_T(""),
	_T(""),
	_T(""),
	_T("제품고정 업"),
	_T("제품고정 다운"),
	_T(""),
	_T(""),
	_T(""),
	_T("-"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),




};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Sleep Mode On"),
	_T("Init Lamp"),
	_T("Reset Lamp"),
	_T("START Lamp"),
	_T("STOP Lamp"),
	_T("-"),
	_T("Towerlamp Red"),
	_T("Towerlamp Yellow"),
	_T("Towerlamp Green"),
	_T("Towerlamp Beep1"),
	_T("Towerlamp Beep2"),
	_T("Front Door1 Lock/Unlock"),
	_T(""),

	_T("Side Left Door1 Lock/Unlock"),
	_T(""),
	_T("Side Left Door2 Lock/Unlock"),
	_T(""),
	_T("Side Left Door3 Lock/Unlock"),
	_T(""),
	_T("Side Right Door1 Lock/Unlock"),
	_T(""),
	_T("Side Right Door2 Lock/Unlock"),
	_T(""),
	_T("Side Right Door3 Lock/Unlock"),
	_T(""),
	_T("Rear Door1 Lock/Unlock"),
	_T(""),
	_T("Rear Door2 Lock/Unlock"),
	_T(""),

	_T(""),
	_T(""),
	_T(""),
	_T("STAU Lock in"),
	_T("STAU Lock Out"),
	_T(""),
	_T(""),
	_T(""),
	_T("-"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),

	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),


};

enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_EMO = 0,
	DIO_INPUT_X0_01_POWER_OFF,
	DIO_INPUT_X0_02_MAIN_PRESSURE,
	DIO_INPUT_X0_03_SLEEP_MODE,
	DIO_INPUT_X0_04_INIT,
	DIO_INPUT_X0_05_SPARE,
	DIO_INPUT_X0_06_START,
	DIO_INPUT_X0_07_STOP,
	DIO_INPUT_X0_08_AREA,
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SPARE,
	DIO_INPUT_X0_0C_SPARE,
	DIO_INPUT_X0_0D_SPARE,
	DIO_INPUT_X0_0E_FRONT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_0F_FRONT_DOOR1_INTERLOCK_OPEN_CLOSE,

	DIO_INPUT_X0_10_SIDE_LEFT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_11_SIDE_LEFT_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_12_SIDE_LEFT_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_13_SIDE_LEFT_DOOR2_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_14_SIDE_LEFT_DOOR3_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_15_SIDE_LEFT_DOOR3_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_16_SIDE_RIGHT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_17_SIDE_RIGHT_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_18_SIDE_RIGHT_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_19_SIDE_RIGHT_DOOR2_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1A_SIDE_RIGHT_DOOR3_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1B_SIDE_RIGHT_DOOR3_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1C_REAR_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1D_REAR_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1E_REAR_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1F_REAR_DOOR2_INTERLOCK_OPEN_CLOSE,

	DIO_INPUT_X1_00_STAU_PRODUCT_L_SENSOR,
	DIO_INPUT_X1_01_STAU_PRODUCT_R_SENSOR,
	DIO_INPUT_X1_02_SPARE,
	DIO_INPUT_X1_03_STAU_L_CYL_IN_CHK_SENSOR,
	DIO_INPUT_X1_04_SPARE,
	DIO_INPUT_X1_05_SPARE,
	DIO_INPUT_X1_06_STAU_R_CYL_IN_CHK_SENSOR,
	DIO_INPUT_X1_07_SPARE,
	DIO_INPUT_X1_08_SPARE,
	DIO_INPUT_X1_09_SPARE,
	DIO_INPUT_X1_0A_SPARE,
	DIO_INPUT_X1_0B_SPARE,
	DIO_INPUT_X1_0C_SPARE,
	DIO_INPUT_X1_0D_SPARE,
	DIO_INPUT_X1_0E_SPARE,
	DIO_INPUT_X1_0F_SPARE,

	DIO_INPUT_X1_10_SPARE,
	DIO_INPUT_X1_11_SPARE,
	DIO_INPUT_X1_12_SPARE,
	DIO_INPUT_X1_13_SPARE,
	DIO_INPUT_X1_14_SPARE,
	DIO_INPUT_X1_15_SPARE,
	DIO_INPUT_X1_16_SPARE,
	DIO_INPUT_X1_17_SPARE,
	DIO_INPUT_X1_18_SPARE,
	DIO_INPUT_X1_19_SPARE,
	DIO_INPUT_X1_1A_SPARE,
	DIO_INPUT_X1_1B_SPARE,
	DIO_INPUT_X1_1C_SPARE,
	DIO_INPUT_X1_1D_SPARE,
	DIO_INPUT_X1_1E_SPARE,
	DIO_INPUT_X1_1F_SPARE,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_SPARE,
	DIO_OUTPUT_Y0_02_SPARE,
	DIO_OUTPUT_Y0_03_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_04_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_06_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_07_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_08_SPARE,
	DIO_OUTPUT_Y0_09_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_0B_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_0C_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0D_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0E_FRONT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_0F_SPARE,

	DIO_OUTPUT_Y0_10_SIDE_LEFT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_11_SPARE,
	DIO_OUTPUT_Y0_12_SIDE_LEFT_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_13_SPARE,
	DIO_OUTPUT_Y0_14_SIDE_LEFT_DOOR3_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_15_SPARE,
	DIO_OUTPUT_Y0_16_SIDE_RIGHT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SIDE_RIGHT_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SIDE_RIGHT_DOOR3_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_REAR_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1D_SPARE,
	DIO_OUTPUT_Y0_1E_REAR_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1F_SPARE,

	DIO_OUTPUT_Y1_00_SPARE,
	DIO_OUTPUT_Y1_01_SPARE,
	DIO_OUTPUT_Y1_02_SPARE,
	DIO_OUTPUT_Y1_03_STAU_CYL_UP,
	DIO_OUTPUT_Y1_04_STAU_CYL_DOWN,
	DIO_OUTPUT_Y1_05_SPARE,
	DIO_OUTPUT_Y1_06_SPARE,
	DIO_OUTPUT_Y1_07_SPARE,
	DIO_OUTPUT_Y1_08_SPARE,
	DIO_OUTPUT_Y1_09_SPARE,
	DIO_OUTPUT_Y1_0A_SPARE,
	DIO_OUTPUT_Y1_0B_SPARE,
	DIO_OUTPUT_Y1_0C_SPARE,
	DIO_OUTPUT_Y1_0D_SPARE,
	DIO_OUTPUT_Y1_0E_SPARE,
	DIO_OUTPUT_Y1_0F_SPARE,

	DIO_OUTPUT_Y1_10_SPARE,
	DIO_OUTPUT_Y1_11_SPARE,
	DIO_OUTPUT_Y1_12_SPARE,
	DIO_OUTPUT_Y1_13_SPARE,
	DIO_OUTPUT_Y1_14_SPARE,
	DIO_OUTPUT_Y1_15_SPARE,
	DIO_OUTPUT_Y1_16_SPARE,
	DIO_OUTPUT_Y1_17_SPARE,
	DIO_OUTPUT_Y1_18_SPARE,
	DIO_OUTPUT_Y1_19_SPARE,
	DIO_OUTPUT_Y1_1A_SPARE,
	DIO_OUTPUT_Y1_1B_SPARE,
	DIO_OUTPUT_Y1_1C_SPARE,
	DIO_OUTPUT_Y1_1D_SPARE,
	DIO_OUTPUT_Y1_1E_SPARE,
	DIO_OUTPUT_Y1_1F_SPARE,
};
#pragma  endregion
#elif(SET_INSPECTOR == SYS_TLA_B)		// GHOST FLARE
#pragma region TLABackup
static LPCTSTR m_szDio_Input_Kor[] =
{
	_T("긴급 정지 버튼"),
	_T("전원 끄기 버튼"),
	_T("메인 압력"),
	_T("슬립 모드"),
	_T("초기화 버튼"),
	_T(""),
	_T("시작"),
	_T("정지"),
	_T("에어리어"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("전면도어1 인터락 온/오프"),
	_T("전면도어1 열림/닫힘"),


	_T("왼쪽도어 1 인터락 온/오프"),
	_T("왼쪽도어 1 열림/닫힘"),
	_T("왼쪽도어 2 인터락 온/오프"),
	_T("왼쪽도어 2 열림/닫힘"),
	_T("왼쪽도어 3 인터락 온/오프"),
	_T("왼쪽도어 3 열림/닫힘"),
	_T("오른쪽도어 1 인터락 온/오프"),
	_T("오른쪽도어 1 열림/닫힘"),
	_T("오른쪽도어 2 인터락 온/오프"),
	_T("오른쪽도어 2 열림/닫힘"),
	_T("오른쪽도어 3 인터락 온/오프"),
	_T("오른쪽도어 3 열림/닫힘"),
	_T("후면도어 1 인터락 온/오프"),
	_T("후면도어 1 열림/닫힘"),
	_T("후면도어 2 인터락 온/오프"),
	_T("후면도어 2 열림/닫힘"),

};

static LPCTSTR m_szDio_Input_Eng[] =
{
	_T("EMO"),
	_T("Power Off"),
	_T("Main Air Pressure"),
	_T("Sleep Mode On Sensor"),
	_T("INIT Button"),
	_T(""),
	_T("START Button"),
	_T("STOP Button"),
	_T("AREA Sensor"),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T(""),
	_T("Front Door1 Lock"),
	_T("Front Door1 Open / Close"),

	_T("Side Left Door1 Lock"),
	_T("Side Left Door1 Open / Close"),
	_T("Side Left Door2 Lock"),
	_T("Side Left Door2 Open / Close"),
	_T("Side Left Door3 Lock"),
	_T("Side Left Door3 Open / Close"),
	_T("Side Right Door1 Lock"),
	_T("Side Right Door1 Open / Close"),
	_T("Side Right Door2 Lock"),
	_T("Side Right Door2 Open / Close"),
	_T("Side Right Door3 Lock"),
	_T("Side Right Door3 Open / Close"),
	_T("Rear Door1 Lock"),
	_T("Rear Door1 Open / Close"),
	_T("Rear Door2 Lock"),
	_T("Rear Door2 Open / Close"),


};

static LPCTSTR m_szDio_Output_Kor[] =
{
	_T("-"),
	_T("-"),
	_T("-"),
	_T("슬립 모드"),
	_T("초기화 버튼"),
	_T("리셋 버튼"),
	_T("시작 버튼"),
	_T("정지 버튼"),
	_T("-"),
	_T("타워램프 빨강"),
	_T("타워램프 노랑"),
	_T("타워램프 녹색"),
	_T("타워램프 알람음1"),
	_T("타워램프 알람음2"),
	_T("전면도어1 인터락 On/Off"),
	_T("-"),

	_T("왼쪽도어 1 인터락 On/Off"),
	_T(""),
	_T("왼쪽도어 2 인터락 On/Off"),
	_T(""),
	_T("왼쪽도어 3 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 1 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 2 인터락 On/Off"),
	_T(""),
	_T("오른쪽도어 3 인터락 On/Off"),
	_T(""),
	_T("후면도어 1 인터락 On/Off"),
	_T(""),
	_T("후면도어 2 인터락 On/Off"),
	_T(""),



};

static LPCTSTR m_szDio_Output_Eng[] =
{
	_T("-"),
	_T("-"),
	_T("-"),
	_T("Sleep Mode On"),
	_T("Init Lamp"),
	_T("Reset Lamp"),
	_T("START Lamp"),
	_T("STOP Lamp"),
	_T("-"),
	_T("Towerlamp Red"),
	_T("Towerlamp Yellow"),
	_T("Towerlamp Green"),
	_T("Towerlamp Beep1"),
	_T("Towerlamp Beep2"),
	_T("Front Door1 Lock/Unlock"),
	_T(""),

	_T("Side Left Door1 Lock/Unlock"),
	_T(""),
	_T("Side Left Door2 Lock/Unlock"),
	_T(""),
	_T("Side Left Door3 Lock/Unlock"),
	_T(""),
	_T("Side Right Door1 Lock/Unlock"),
	_T(""),
	_T("Side Right Door2 Lock/Unlock"),
	_T(""),
	_T("Side Right Door3 Lock/Unlock"),
	_T(""),
	_T("Rear Door1 Lock/Unlock"),
	_T(""),
	_T("Rear Door2 Lock/Unlock"),
	_T(""),
};

enum DIGITAL_INPUT
{
	DIO_INPUT_X0_00_EMO = 0,
	DIO_INPUT_X0_01_POWER_OFF,
	DIO_INPUT_X0_02_MAIN_PRESSURE,
	DIO_INPUT_X0_03_SLEEP_MODE,
	DIO_INPUT_X0_04_INIT,
	DIO_INPUT_X0_05_SPARE,
	DIO_INPUT_X0_06_START,
	DIO_INPUT_X0_07_STOP,
	DIO_INPUT_X0_08_AREA,
	DIO_INPUT_X0_09_SPARE,
	DIO_INPUT_X0_0A_SPARE,
	DIO_INPUT_X0_0B_SPARE,
	DIO_INPUT_X0_0C_SPARE,
	DIO_INPUT_X0_0D_SPARE,
	DIO_INPUT_X0_0E_FRONT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_0F_FRONT_DOOR1_INTERLOCK_OPEN_CLOSE,

	DIO_INPUT_X0_10_SIDE_LEFT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_11_SIDE_LEFT_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_12_SIDE_LEFT_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_13_SIDE_LEFT_DOOR2_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_14_SIDE_LEFT_DOOR3_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_15_SIDE_LEFT_DOOR3_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_16_SIDE_RIGHT_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_17_SIDE_RIGHT_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_18_SIDE_RIGHT_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_19_SIDE_RIGHT_DOOR2_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1A_SIDE_RIGHT_DOOR3_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1B_SIDE_RIGHT_DOOR3_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1C_REAR_DOOR1_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1D_REAR_DOOR1_INTERLOCK_OPEN_CLOSE,
	DIO_INPUT_X0_1E_REAR_DOOR2_INTERLOCK_ON_OFF,
	DIO_INPUT_X0_1F_REAR_DOOR2_INTERLOCK_OPEN_CLOSE,
};

enum DIGITAL_OUTPUT
{
	DIO_OUTPUT_Y0_00_SPARE = 0,
	DIO_OUTPUT_Y0_01_SPARE,
	DIO_OUTPUT_Y0_02_SPARE,
	DIO_OUTPUT_Y0_03_SLEEP_MODE_ON,
	DIO_OUTPUT_Y0_04_INIT_SWITCH_LAMP,
	DIO_OUTPUT_Y0_05_RESET_SWITCH_LAMP,
	DIO_OUTPUT_Y0_06_START_SWITCH_LAMP,
	DIO_OUTPUT_Y0_07_STOP_SWITCH_LAMP,
	DIO_OUTPUT_Y0_08_SPARE,
	DIO_OUTPUT_Y0_09_TOWERLAMP_RED,
	DIO_OUTPUT_Y0_0A_TOWERLAMP_YELLOW,
	DIO_OUTPUT_Y0_0B_TOWERLAMP_GREEN,
	DIO_OUTPUT_Y0_0C_TOWERLAMP_BEEP1,
	DIO_OUTPUT_Y0_0D_TOWERLAMP_BEEP2,
	DIO_OUTPUT_Y0_0E_FRONT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_0F_SPARE,

	DIO_OUTPUT_Y0_10_SIDE_LEFT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_11_SPARE,
	DIO_OUTPUT_Y0_12_SIDE_LEFT_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_13_SPARE,
	DIO_OUTPUT_Y0_14_SIDE_LEFT_DOOR3_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_15_SPARE,
	DIO_OUTPUT_Y0_16_SIDE_RIGHT_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_17_SPARE,
	DIO_OUTPUT_Y0_18_SIDE_RIGHT_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_19_SPARE,
	DIO_OUTPUT_Y0_1A_SIDE_RIGHT_DOOR3_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1B_SPARE,
	DIO_OUTPUT_Y0_1C_REAR_DOOR1_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1D_SPARE,
	DIO_OUTPUT_Y0_1E_REAR_DOOR2_INTERLOCK_ONOFF,
	DIO_OUTPUT_Y0_1F_SPARE,
};
#pragma  endregion
#endif

// IO Dlg End
//-------------------------------------------------------------------------

